version: '3'

services:
  app:
    container_name: borgmatic
    image: b3vis/borgmatic:1.8.8
    restart: "unless-stopped"
    networks:
      - default
    env_file:
      - ./app.env
    volumes:
      - /opt/docker-compose:/mnt/source:ro
      - ./config.yaml:/etc/borgmatic.d/config.yaml
      - ./excluded.txt:/etc/borgmatic.d/excluded.txt:ro
      - ./data/config:/root/.config/borg
      - ./data/ssh:/root/.ssh
      - ./data/cache:/root/.cache/borg
      - ./data/borgmatic:/etc/borgmatic.d
      - ./data/root:/root/.borgmatic

networks:
  default:
    name: borgmatic
    driver: bridge
    enable_ipv6: false

