services:
  app:
    container_name: borgmatic
    image: b3vis/borgmatic:2.0.6
    restart: "unless-stopped"
    networks:
      - default
    env_file:
      - ./app.env
    volumes:
      - /opt/docker-compose:/backup/docker-compose:ro
      - ./config.yaml:/etc/borgmatic.d/config.yaml
      - ./excluded.txt:/etc/borgmatic.d/excluded.txt:ro
      - ./data/config:/root/.config/borg
      - ./data/ssh:/root/.ssh
      - ./data/cache:/root/.cache/borg
      - ./data/borgmatic:/etc/borgmatic.d
      - ./data/borg-repository:/mnt/borg-repository
      - ./data/root:/root/.borgmatic
      - ./data/source:/mnt/source:ro
      - ./data/state:/root/.local/state/borgmatic

networks:
  default:
    name: borgmatic
    driver: bridge
    enable_ipv6: false

